CREATE TABLE IF NOT EXISTS listings (
    id                  SERIAL      PRIMARY KEY,
    item_id             TEXT        NOT NULL,
    source              TEXT        NOT NULL,
    city                TEXT,
    url                 TEXT,
    title               TEXT,
    price               INTEGER,
    published_at        TIMESTAMP,
    address             TEXT,
    metro               TEXT[],
    description         TEXT,
    property_type       TEXT,
    rooms               INTEGER,
    room_type           TEXT,
    floor               INTEGER,
    area_total          NUMERIC(8,2),
    area_living         NUMERIC(8,2),
    area_kitchen        NUMERIC(8,2),
    ceiling_height      NUMERIC(4,2),
    renovation          TEXT,
    bathroom            TEXT,
    windows             TEXT,
    furniture           TEXT,
    appliances          TEXT,
    balcony             BOOLEAN,
    loggia              BOOLEAN,
    wardrobe            BOOLEAN,
    panoramic_windows   BOOLEAN,
    warm_floor          BOOLEAN,
    house_type          TEXT,
    total_floors        INTEGER,
    year_built          INTEGER,
    passenger_elevator  INTEGER,
    cargo_elevator      INTEGER,
    yard                TEXT,
    parking             TEXT,
    concierge           BOOLEAN,
    garbage_chute       BOOLEAN,
    gas                 BOOLEAN,
    demolition_planned  BOOLEAN,
    sale_method         TEXT,
    sale_conditions     TEXT,
    developer           TEXT,
    sale_type           TEXT,
    lat                 NUMERIC(10,7),
    lon                 NUMERIC(10,7),
    parsed_at           TIMESTAMP   DEFAULT NOW(),

    UNIQUE (item_id, source)
);
